---
title: "project4_paper5_k-means"
author: "Yaqin Li (yl3578)"
date: "4/8/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Packages

```{r}
packages<-c("stringr", "text2vec","plyr")

# Check packages that need to be installed.
packages.needed<-setdiff(packages, intersect(installed.packages()[,1], 
                                                 packages))

# Install packages
if(length(packages.needed)>0){
  install.packages(packages.needed, dependencies = TRUE,
                   repos='http://cran.us.r-project.org')
}

# Load packages
library(stringr)
library(text2vec)
library(plyr)
```

##Data Input
```{r}
names<-list.files(path = "../data/nameset", pattern = "*.txt")

names <- substr(names, 1, nchar(names)-4)

authors <- paste(substring(names, 1, 1), " ", 
                 substring(names, 2, nchar(names)), sep="")

dataset <- list(length(names))

for(i in 1:length(names)){
  dataset[[i]]<-list(3)
  dataset[[i]][[1]]<-authors[i]
  dataset[[i]][[2]]<- readLines(paste0("../data/nameset/", names[i],".txt"))
  dataset[[i]][[3]]<-length(dataset[[i]][[2]])
}
```

##Data frame

```{r}
df_form<-function(l){
  df1<-do.call(rbind,str_split(l[[2]],"<>"))
  
  pattern1<-"[0-9]+_[0-9]+"
  
  pattern2<-strsplit(l[[1]]," ")
  pattern2<-paste0(pattern2[[1]][1],"[a-z]?\ ",pattern2[[1]][2],"[:punct:]?[;]?[:punct:]?")
  
  #Author ID and Paper NO.
  ID<-unlist(regmatches(df1[,1], gregexpr(pattern1, df1[,1])))
  n1<-nchar(ID)
  ID<-do.call(rbind,str_split(ID,"_"))
  
  #Title of Paper
  paper<-df1[,2]
  
  #Journal
  journal<-df1[,3]
  
  #Author name
  quest_author<-rep(l[[1]],l[[3]])
  
  #Coauthor
  coauthor<-sub(paste0(pattern1," "),"",df1[,1])
  coauthor<-sub(pattern2,"",coauthor)

  
  df<-data.frame(author.id=ID[,1],paper.no=ID[,2],quest_author=quest_author,coauthor=coauthor,paper=paper,journal=journal)
  return(df)
}

df<-llply(dataset,df_form)

save(df,file="../output/dataframe.Rdata")
df1<-df[[1]]
```

##K-means

```{r}

load(file="../output/feature1.Rdata")
colnames(f1)[1:3]<-colnames(df1)[1:3]

update1<-function(mu1,mu2,a){
  d<-abs(mu2-mu1)
  a<-a*(1+d/sum(d))
  return(a)
}
update2<-function(mu.t,mu.f,err,a){
  d.t<-abs(mu.t-err)+0.001
  d.f<-abs(mu.f-err)
  a<-a*sqrt(d.f/d.t)
  return(a)
}

dist<-function(a1,a2,l){
    n<-length(a1)
    x<-(a1-a2)^2
    x<-l*x
    return(sum(x))
  }



train<-function(df){
  y<-df[,1]
  df<-df[,-1:-3]
  df<-matrix(unlist(df),nrow(df),ncol(df))
  
  l<-levels(factor(y))
  K<-length(l)
  max.iteration<-10
  d<-ncol(df)
  lambda<-rep(0,d)
  lambda.new<-rep(1,d)
  weight<-rep(1,d)
  j<-0
  
  cluster<-list()
  u<-list()
  first_point<-function(t){
    return(t[1])
  }
  d<-tapply(1:nrow(df),y,first_point)
  for(i in 1:K){
    cluster[[i]]<-c(d[i])
    u[[i]]<-df[d[i],]
    #u[[i]]<-unlist(df[d[i],-c(1,2,3)])
  }
  l<-y[d]
  
  while (dist(lambda,lambda.new,weight)>0.1 & j<=max.iteration){
    j<-j+1
    lambda<-lambda.new
    for (i in 1:nrow(df)){
      distance<-c()
      for (k in 1:K){
        distance<-c(distance,dist(df[i,],u[[k]],lambda.new))
        #distance<-c(distance,dist(unlist(df[i,-c(1,2,3)]),u[[k]],lambda.new))
      }
      m<-which.min(distance)
      r<-which(l==y[i])
      if (m!=r){
        #lambda.new<-update1(u[[r]],u[[m]],lambda.new)
        lambda.new<-update2(u[[r]],u[[m]],df[i,],lambda)
        m<-r
      }
      cluster[[m]]<-c(cluster[[m]],i)
      u[[m]]<-colMeans(df[cluster[[m]],])
      
      # #u[[m]]<-df[cluster[[m]][1],-c(1,2,3)]
      # u[[m]]<-unlist(df[cluster[[m]][1],-c(1,2,3)])
      # for(s in 2:length(cluster[[m]])){
      #   #u[[m]]<-u[[m]]+df[cluster[[m]][s],-c(1,2,3)]
      #   u[[m]]<-u[[m]]+unlist(df[cluster[[m]][s],-c(1,2,3)])
      # }
      # u[[m]]<-u[[m]]/length(cluster[[m]])
    }
  }
  
  u2<-unlist(u[[1]])
  for (s in 2:K){
    u2<-rbind(u2,unlist(u[[s]]))
  }
  
  return(list(lambda=lambda.new,K,label=y,center=u2,iteration=j))
  
}

#test
te<-sample(1:nrow(f1),10,replace = TRUE)
f2<-f1[te,]
f1<-f1[-te,]
time<-system.time(flambda<-train(f1))

test<-function(df,lambda,K,label,center){
  y<-df[,1]
  df<-df[,-1:-3]
  df<-matrix(unlist(df),nrow(df),ncol(df))
  y2<-c()
  for (i in 1:nrow(df)){
      distance<-c()
      for (k in 1:K){
        distance<-c(distance,dist(df[i,],center[k,],lambda))
        
      }
      m<-which.min(distance)
      y2<-c(y2,m)
    }
  
  y2<-label[y2]
  accuracy<-mean(y==y2)
  return(list(y2,y,accuracy))
}

result<-test(f2,flambda$lambda,flambda[[2]],flambda$label,flambda$center)
result2<-test(f1,flambda$lambda,flambda[[2]],flambda$label,flambda$center)

```

