---
title: "Main_lyf"
author: "Yifei Lin"
date: "April 11, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Generate Feature for Paper 5
```{r}
if (!require(stringr)) {install.packages(stringr)}
library(stringr)
source("../lib/lyf_helper.R")
source("../lib/feature_helper.R")
```

```{r}
data.lib="../data/nameset"
data.files=list.files(path=data.lib, "*.txt")
query.list=substring(data.files, 
                     1, nchar(data.files)-4)
query.list=paste(substring(query.list, 1, 1), 
                 " ", 
                 substring(query.list, 
                           2, nchar(query.list)),
                 sep=""
                 )
data_list=list(1:length(data.files))
for(i in 1:length(data.files)){
  dat=as.list(readLines(paste(data.lib, data.files[i], sep="/")))
  data_list[[i]]=lapply(dat, f.line.proc, nam.query=query.list[i])
}
```

## Text 1
```{r}
feature <- list()

for (j in 1:14) {
authorid<- c()
for (i in 1:length(data_list[[j]])) {
  authorid[i] <- data_list[[j]][[i]][1]
}
authorid<-unlist(authorid)
paperid<-c()
for (i in 1:length(data_list[[j]])) {
  paperid[i] <- data_list[[j]][[i]][2]
}
paperid<-unlist(paperid)
authorname<- query.list[j]
feature[[j]]<- cbind(authorid,paperid,authorname,f.coauthor(authorname),f.journal(authorname), f.ptitle(authorname))

}
save(feature,file="../output/feature.Rdata")

```

