---
title: "project4_paper5_k-means"
author: "Yaqin Li (yl3578)"
date: "4/8/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Packages

```{r}
packages<-c("stringr", "text2vec","plyr")

# Check packages that need to be installed.
packages.needed<-setdiff(packages, intersect(installed.packages()[,1], 
                                                 packages))

# Install packages
if(length(packages.needed)>0){
  install.packages(packages.needed, dependencies = TRUE,
                   repos='http://cran.us.r-project.org')
}

# Load packages
library(stringr)
library(text2vec)
library(plyr)
```

##K-means

```{r}

update1<-function(mu1,mu2,a){
  d<-abs(mu2-mu1)
  a<-a*(1+d/sum(d))
  return(a)
}
update2<-function(mu.t,mu.f,err,a){
  d.t<-abs(mu.t-err)+1
  d.f<-abs(mu.f-err)+1
  a<-a*(d.f/d.t)
  return(a)
}

dist<-function(a1,a2,l){
    n<-length(a1)
    x<-(a1-a2)^2
    x<-l*x
    return(sum(x))
  }



train<-function(df){
  y<-df[,1]
  df<-df[,-1:-3]
  df<-matrix(unlist(df),nrow(df),ncol(df))
  
  l<-levels(factor(y))
  K<-length(l)
  max.iteration<-10
  d<-ncol(df)
  lambda<-rep(0,d)
  lambda.new<-rep(1,d)
  weight<-rep(1,d)
  j<-0
  
  cluster<-list()
  u<-list()
  first_point<-function(t){
    return(t[1])
  }
  d<-tapply(1:nrow(df),y,first_point)
  for(i in 1:K){
    cluster[[i]]<-c(d[i])
    u[[i]]<-df[d[i],]
    #u[[i]]<-unlist(df[d[i],-c(1,2,3)])
  }
  l<-y[d]
  
  while (dist(lambda,lambda.new,weight)>0.01 & j<=max.iteration){
    j<-j+1
    lambda<-lambda.new
    for (i in 1:nrow(df)){
      distance<-c()
      for (k in 1:K){
        distance<-c(distance,dist(df[i,],u[[k]],lambda.new))
        #distance<-c(distance,dist(unlist(df[i,-c(1,2,3)]),u[[k]],lambda.new))
      }
      m<-which.min(distance)
      r<-which(l==y[i])
      if (m!=r){
        #lambda.new<-update1(u[[r]],u[[m]],lambda.new)
        lambda.new<-update2(u[[r]],u[[m]],df[i,],lambda)
        m<-r
      }
      cluster[[m]]<-c(cluster[[m]],i)
      u[[m]]<-colMeans(df[cluster[[m]],])
      
      # #u[[m]]<-df[cluster[[m]][1],-c(1,2,3)]
      # u[[m]]<-unlist(df[cluster[[m]][1],-c(1,2,3)])
      # for(s in 2:length(cluster[[m]])){
      #   #u[[m]]<-u[[m]]+df[cluster[[m]][s],-c(1,2,3)]
      #   u[[m]]<-u[[m]]+unlist(df[cluster[[m]][s],-c(1,2,3)])
      # }
      # u[[m]]<-u[[m]]/length(cluster[[m]])
    }
  }
  
  u2<-unlist(u[[1]])
  for (s in 2:K){
    u2<-rbind(u2,unlist(u[[s]]))
  }
  
  return(list(lambda=lambda.new,K,label=y,center=u2,iteration=j))
  
}

#test
load(file="../output/feature1.Rdata")
te<-sample(1:nrow(f1),100,replace = TRUE)
f2<-f1[te,]
f1<-f1[-te,]
time<-system.time(flambda<-train(f1))

# test<-function(df,lambda,K,label,center){
#   y<-df[,1]
#   df<-df[,-1:-3]
#   df<-matrix(unlist(df),nrow(df),ncol(df))
#   y2<-c()
#   for (i in 1:nrow(df)){
#       distance<-c()
#       for (k in 1:K){
#         distance<-c(distance,dist(df[i,],center[k,],lambda))
#         
#       }
#       m<-which.min(distance)
#       y2<-c(y2,m)
#     }
#   
#   y2<-label[y2]
#   accuracy<-mean(y==y2)
#   return(list(y2,y,accuracy))
# }

test2<-function(df,lambda){
  y<-df[,1]
  k<-length(unique(y))
  df<-df[,-1:-3]
  df<-matrix(unlist(df),nrow(df),ncol(df))
  km_new<-function(x,a,k){
  for(i in 1:ncol(x)){
    x[,i]<-x[,i]*sqrt(a[i])
  }
  cl<-kmeans(x,k)
  return(cl)
}
  y2<-km_new(df,lambda,k)
  
  cluster<-function(x){
    return(length(x)-max(table(x)))
  }
  
  error<-tapply(y,y2$cluster,cluster)
  return(list(y2$cluster,y,accuracy=(length(y)-sum(error))/length(y)))
}

# result<-test(f2,flambda$lambda,flambda[[2]],flambda$label,flambda$center)
# result2<-test(f1,flambda$lambda,flambda[[2]],flambda$label,flambda$center)
re<-test2(f2,flambda$lambda)

```


##evaluation:error and running time

```{r}
load(file="../output/feature.Rdata")
time<-c()
accuracy<-c()

for(i in 1:14){
  f1<-feature[[i]]
  te<-sample(1:nrow(f1),100,replace = TRUE)
  f2<-f1[te,]
  #f1<-f1[-te,]
  t1<-Sys.time()
  flambda<-train(f1)
  t2<-Sys.time()
  time<-c(time,t2-t1)
  re<-test2(f2,flambda$lambda)
  accuracy<-c(accuracy,re$accuracy)
}

e<-cbind(accuracy,time)
m<-colMeans(e)
e<-rbind(e,m)
save(e,file="../output/accuracy.Rdata")

```

